const {
  CHECKPOINT_CREATED,
  DEFAULT_AUDIT_TYPES,
  HANDOFF_UPDATED,
  PROVIDER_EXECUTION_COMPLETED,
  PROVIDER_EXECUTION_FAILED,
  PROVIDER_EXECUTION_REQUESTED,
  FALLBACK_TRIGGERED,
  RETRY_BUDGET_EXHAUSTED,
  PROVIDER_DISCOVERY_RUN,
  PROVIDER_HEALTH_ALERT_ACKED,
  PROVIDER_HEALTH_ALERT_CREATED,
  DISCUSSION_COMPLETED,
  DISCUSSION_DECISION_RECORDED,
  DISCUSSION_STARTED,
  AUTHORIZATION_RESOLVED,
  GOVERNANCE_AUTH_REQUESTED,
  GOVERNANCE_BUDGET_BLOCKED,
  GOVERNANCE_CACHE_HIT,
  GOVERNANCE_CONTEXT_COMPRESSED,
  HANDOFF_SNAPSHOT_CREATED,
  IM_COMMAND_RECEIVED,
  IM_COMMAND_ROUTED,
  INTERRUPTED_TASK_RECOVERED,
  LOCAL_RUNNER_OPERATION_BLOCKED,
  LOCAL_RUNNER_OPERATION_COMPLETED,
  MCP_SERVER_MOUNTED,
  POLICY_RULE_CREATED,
  REDACTED_VALUE,
  SELF_REFLECTION_RECORDED,
  SHADOW_EXECUTION_COMPLETED,
  SHADOW_EXECUTION_FAILED,
  SKILL_PROPOSAL_CREATED,
  SKILL_PROPOSAL_RESOLVED,
  TAKEOVER_ACTION_RECEIVED,
  TAKEOVER_NOTIFICATION_SENT,
  TAKEOVER_REQUESTED,
  ROLLBACK_EXECUTED,
  STEP_LOGGED,
  redactSensitiveData,
  createAuditEvent
} = require("./audit");
const {
  CHECKPOINT_ID_PATTERN,
  STEP_ID_PATTERN,
  ValidationError,
  hashPayload,
  nowUtcIso,
  validateAuditEvent,
  validateHandoffSnapshot,
  validateRollbackCheckpoint,
  validateStepRecord
} = require("./contracts");
const { DEFAULT_FLAGS, fromMapping, highRiskFlagsDisabled, loadFeatureFlags } = require("./featureFlags");
const {
  ensureDir,
  materializePortablePath,
  normalizePortablePath,
  readJsonFile,
  resolveDataPath,
  resolveDataRoot,
  resolveProjectPath,
  writeJsonFile
} = require("./appPaths");
const {
  AuthorizationRequiredError,
  AuthorizationWorkflowManager,
  JsonFileAuthorizationRequestStore,
  inferPermanentGrant
} = require("./authorizationWorkflow");
const { JsonlStepJournal, STEP_STATUSES } = require("./checkpointJournal");
const { GitSafetyManager, runGit } = require("./gitSafety");
const { FORBIDDEN_PATHS, LocalExecutor, ResourceGuardian, assertForbiddenPath } = require("./localExecutor");
const { JsonFilePolicyStore, BUDGET_RULE_SCOPE, PATH_RULE_SCOPE, SKILL_RULE_SCOPE } = require("./policyStore");
const { McpRegistry } = require("./mcpRegistry");
const {
  DEFAULT_SECRET_AUDIT_PATH,
  DEFAULT_SECRET_VAULT_PATH,
  JsonFileSecretVault,
  decryptSecret,
  encryptSecret,
  maskSecretValue
} = require("./secretVault");
const { SkillRegistry, scanPythonCode } = require("./skillsRegistry");
const { analyzeSentiment, narrateSystemStatus } = require("./statusNarrator");
const { createChildTraceId, createTraceId, ensureTraceId } = require("./trace");
const { scrubSensitiveData, scrubString } = require("./sensitiveData");

module.exports = {
  AUTHORIZATION_RESOLVED,
  AuthorizationRequiredError,
  AuthorizationWorkflowManager,
  BUDGET_RULE_SCOPE,
  CHECKPOINT_CREATED,
  CHECKPOINT_ID_PATTERN,
  DEFAULT_AUDIT_TYPES,
  DEFAULT_FLAGS,
  FORBIDDEN_PATHS,
  GOVERNANCE_AUTH_REQUESTED,
  GOVERNANCE_BUDGET_BLOCKED,
  GOVERNANCE_CACHE_HIT,
  GOVERNANCE_CONTEXT_COMPRESSED,
  HANDOFF_UPDATED,
  HANDOFF_SNAPSHOT_CREATED,
  IM_COMMAND_RECEIVED,
  IM_COMMAND_ROUTED,
  INTERRUPTED_TASK_RECOVERED,
  JsonFileAuthorizationRequestStore,
  JsonFilePolicyStore,
  JsonlStepJournal,
  GitSafetyManager,
  LocalExecutor,
  LOCAL_RUNNER_OPERATION_BLOCKED,
  LOCAL_RUNNER_OPERATION_COMPLETED,
  MCP_SERVER_MOUNTED,
  McpRegistry,
  PATH_RULE_SCOPE,
  POLICY_RULE_CREATED,
  PROVIDER_EXECUTION_COMPLETED,
  PROVIDER_EXECUTION_FAILED,
  PROVIDER_EXECUTION_REQUESTED,
  FALLBACK_TRIGGERED,
  RETRY_BUDGET_EXHAUSTED,
  PROVIDER_DISCOVERY_RUN,
  PROVIDER_HEALTH_ALERT_ACKED,
  PROVIDER_HEALTH_ALERT_CREATED,
  ResourceGuardian,
  DISCUSSION_COMPLETED,
  DISCUSSION_DECISION_RECORDED,
  DISCUSSION_STARTED,
  REDACTED_VALUE,
  SELF_REFLECTION_RECORDED,
  SHADOW_EXECUTION_COMPLETED,
  SHADOW_EXECUTION_FAILED,
  SKILL_PROPOSAL_CREATED,
  SKILL_PROPOSAL_RESOLVED,
  SKILL_RULE_SCOPE,
  SkillRegistry,
  STEP_STATUSES,
  DEFAULT_SECRET_AUDIT_PATH,
  DEFAULT_SECRET_VAULT_PATH,
  TAKEOVER_ACTION_RECEIVED,
  TAKEOVER_NOTIFICATION_SENT,
  TAKEOVER_REQUESTED,
  ROLLBACK_EXECUTED,
  STEP_ID_PATTERN,
  STEP_LOGGED,
  ValidationError,
  assertForbiddenPath,
  createChildTraceId,
  createTraceId,
  redactSensitiveData,
  createAuditEvent,
  ensureDir,
  ensureTraceId,
  fromMapping,
  inferPermanentGrant,
  JsonFileSecretVault,
  decryptSecret,
  encryptSecret,
  hashPayload,
  highRiskFlagsDisabled,
  loadFeatureFlags,
  materializePortablePath,
  maskSecretValue,
  narrateSystemStatus,
  nowUtcIso,
  normalizePortablePath,
  readJsonFile,
  resolveDataPath,
  resolveDataRoot,
  resolveProjectPath,
  runGit,
  scanPythonCode,
  scrubSensitiveData,
  scrubString,
  analyzeSentiment,
  validateAuditEvent,
  validateHandoffSnapshot,
  validateRollbackCheckpoint,
  validateStepRecord,
  writeJsonFile
};
