const {
  CHECKPOINT_CREATED,
  DEFAULT_AUDIT_TYPES,
  HANDOFF_UPDATED,
  PROVIDER_EXECUTION_COMPLETED,
  PROVIDER_EXECUTION_FAILED,
  PROVIDER_EXECUTION_REQUESTED,
  FALLBACK_TRIGGERED,
  RETRY_BUDGET_EXHAUSTED,
  PROVIDER_DISCOVERY_RUN,
  PROVIDER_HEALTH_ALERT_ACKED,
  PROVIDER_HEALTH_ALERT_CREATED,
  DISCUSSION_COMPLETED,
  DISCUSSION_DECISION_RECORDED,
  DISCUSSION_STARTED,
  REDACTED_VALUE,
  TAKEOVER_ACTION_RECEIVED,
  TAKEOVER_NOTIFICATION_SENT,
  TAKEOVER_REQUESTED,
  ROLLBACK_EXECUTED,
  STEP_LOGGED,
  redactSensitiveData,
  createAuditEvent
} = require("./audit");
const {
  CHECKPOINT_ID_PATTERN,
  STEP_ID_PATTERN,
  ValidationError,
  hashPayload,
  nowUtcIso,
  validateAuditEvent,
  validateHandoffSnapshot,
  validateRollbackCheckpoint,
  validateStepRecord
} = require("./contracts");
const { DEFAULT_FLAGS, fromMapping, highRiskFlagsDisabled, loadFeatureFlags } = require("./featureFlags");
const {
  DEFAULT_SECRET_AUDIT_PATH,
  DEFAULT_SECRET_VAULT_PATH,
  JsonFileSecretVault,
  decryptSecret,
  encryptSecret,
  maskSecretValue
} = require("./secretVault");

module.exports = {
  CHECKPOINT_CREATED,
  CHECKPOINT_ID_PATTERN,
  DEFAULT_AUDIT_TYPES,
  DEFAULT_FLAGS,
  HANDOFF_UPDATED,
  PROVIDER_EXECUTION_COMPLETED,
  PROVIDER_EXECUTION_FAILED,
  PROVIDER_EXECUTION_REQUESTED,
  FALLBACK_TRIGGERED,
  RETRY_BUDGET_EXHAUSTED,
  PROVIDER_DISCOVERY_RUN,
  PROVIDER_HEALTH_ALERT_ACKED,
  PROVIDER_HEALTH_ALERT_CREATED,
  DISCUSSION_COMPLETED,
  DISCUSSION_DECISION_RECORDED,
  DISCUSSION_STARTED,
  REDACTED_VALUE,
  DEFAULT_SECRET_AUDIT_PATH,
  DEFAULT_SECRET_VAULT_PATH,
  TAKEOVER_ACTION_RECEIVED,
  TAKEOVER_NOTIFICATION_SENT,
  TAKEOVER_REQUESTED,
  ROLLBACK_EXECUTED,
  STEP_ID_PATTERN,
  STEP_LOGGED,
  ValidationError,
  redactSensitiveData,
  createAuditEvent,
  fromMapping,
  JsonFileSecretVault,
  decryptSecret,
  encryptSecret,
  hashPayload,
  highRiskFlagsDisabled,
  loadFeatureFlags,
  maskSecretValue,
  nowUtcIso,
  validateAuditEvent,
  validateHandoffSnapshot,
  validateRollbackCheckpoint,
  validateStepRecord
};
